server:
  port: 2525

# 该配置的名称是固定的，不可以改变，否则将不能自动加载到数据源中
spring:
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.3.172:3306/poc?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: devuser
    password: dev123
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20


#mysql :
#  #jdbc
#  driver : com.mysql.jdbc.Driver
#  url : jdbc:mysql://192.168.3.172:3306/poc?useUnicode=true&characterEncoding=utf8
#  username : devuser
#  password : dev123
#  #初始化连接数个数
#  initialSize : 5
#  #最大连接数
#  maxActive : 2335
#  #配置获取连接等待超时的时间
#  maxWait : 100


